import type { Metadata } from 'next';
import { Geist_Mono, Playfair_Display, Poppins } from 'next/font/google';

import '../globals.css';

import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { setRequestLocale } from 'next-intl/server';

import FooterSection from '@/components/layout/footer';
import { NavMenu } from '@/components/layout/header';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { routing } from '@/i18n/routing';

const poppins = Poppins({
    variable: '--font-geist-sans',
    display: 'swap',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const playfairDisplay = Playfair_Display({
    variable: '--font-geist-serif',
    display: 'swap',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Ensure that the incoming `locale` is valid
    const { locale } = await params;
    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    // Enable static rendering
    setRequestLocale(locale);
    return (
        <html lang={locale} suppressHydrationWarning>
            <body
                className={`${poppins.variable} ${geistMono.variable} ${playfairDisplay.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextIntlClientProvider>
                        {/* <HeroSection /> */}
                        <NavMenu />
                        {children}
                        <FooterSection />
                        <Toaster />
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
